kind = "web"
previewPath = "/"
title = "Sercaw"
version = "1.0.0"
id = "artifacts/sercaw"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22684

[services.development]
run = "pnpm --filter @workspace/sercaw run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/sercaw", "run", "build" ]
serve = "static"
publicDir = "artifacts/sercaw/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22684"
BASE_PATH = "/"
